changelog.d/+operator-waitlist.internal.md, package.json, src/api.ts, src/debugger.ts, src/extension.ts, src/waitlist.ts
closes metalbear-co/mirrord#1503 & metalbear-co/mirrord#1306
=> Add mirrord teams waitlist signup command

changelog.d/+rollout.internal.md, src/api.ts, src/debugger.ts, src/tests/e2e.ts, tsconfig.json
Add support for argo Rollout target or any future targets added mirrord and returned via `mirrord ls`
=> Add support for Rollout

changelog.d/32.fixed.md, src/debugger.ts
=> Fixed Debug launch failing on Java applications

changelog.d/24.added.md, package.json, src/api.ts, src/config.ts, src/debugger.ts, src/notification.ts, src/status.ts, src/versionCheck.ts, src/waitlist.ts
Closes #24 
1. Implemented a generic notification builder for adding common actions to notifications.
2. Added `Don't show again` action to most notifications and fixed this option were it was already implemented (respective configuration options were not declared in `contributes` entry in `package.json`
3. Fixed status bar menu not updating when active config file has been removed/renamed
=> Disable notifications

changelog.d/6.added.md, package.json, src/binaryManager.ts
=> Specify mirrord binary in settings

changelog.d/62.added.md, package-lock.json, package.json, src/api.ts
- Issue: #36 
Adds a global counter that asks the user to leave feedback after 100 runs of mirrord, (then it resets itself?).
=> Add feedback request when mirrord runs 100 times (#36).

changelog.d/52.fixed.md, package.json, src/api.ts, src/status.ts
Closes #52
Marketplace review prompt is now displayed after each 100 runs and can be disabled.
Feedback action (google forms) was already there
=> Feedback fix

changelog.d/+dependency-bumped.internal.md, package-lock.json
Bumped dependency, because `npm install` shows vulnerability
=> Dependency bump

.github/workflows/ci.yaml, .github/workflows/reusable_e2e.yaml, changelog.d/+binary-download.fixed.md, src/binaryManager.ts, src/debugger.ts, src/extension.ts
Fix error when loading into Windows VSCode and improve binary fetching code
=> Fix error when loading into Windows VSCode and improve binary fetching

changelog.d/+increase-timeout.internal.md, src/tests/e2e.ts
=> Increase timeout on waiting for debugging to start in e2e tests

changelog.d/382.added.md, src/api.ts
- Issue: [#382](https://github.com/metalbear-co/operator/issues/382)
- Notifies user on how many days they have on their operator license, with a warning if its close to expiring.
=> Notify user on how many days they have on their operator license.

changelog.d/100.added.md, src/api.ts, src/mirrordForTeams.ts, src/notification.ts, src/tests/e2e.ts
=> Handle new message type from mirrord, and dont display multipod warning if its using the operator.

changelog.d/114.added.md, package.json, src/api.ts
=> Add message inviting user to Discord every 10 usages

changelog.d/120.fixed.md, src/api.ts, src/debugger.ts, src/mirrordForTeams.ts, src/status.ts
=> disabling mfT notification and menu item after first operator usage

.github/workflows/ci.yaml, changelog.d/137.fixed.md, src/debugger.ts
Part of the fix for #137 along with https://github.com/metalbear-co/mirrord/pull/2623
=> Add config type debugpy for detecting debugger port

changelog.d/131.added.md, package.json, src/extension.ts
=> Allow mirrord to be enabled or disabled by default in settings

changelog.d/144.fixed.md, src/binaryManager.ts
=> Handling empty version string in `mirrord.autoUpdate`, improved auto update notifications

changelog.d/148.internal.md, src/api.ts
=> Link query param

changelog.d/+explicitly-disable-from-env.added.md, src/debugger.ts
Parity with https://github.com/metalbear-co/mirrord-intellij/pull/298
=> Explicitly disable plugin when `MIRRORD_ACTIVE=0`

README.md, changelog.d/+newsletter-notification.internal.md, package.json, src/api.ts, src/status.ts
Issue: https://linear.app/metalbear/issue/MBE-1033/oss-redirect-to-newsletter-via-ide
=> Add notification for mirrord newsletter
